name: CI/CD Pipeline with GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    # - name: Lint with pylint
    #   run: |
    #     make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format

  build-and-push-to-dockerhub:
    name: Build and Push to Docker Hub
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_HUB_REPO_NAME}}:latest

  deploy-to-azure:
    name: Deploy to Azure App Service
    runs-on: ubuntu-latest
    needs: build-and-push-to-dockerhub

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/setup-azure@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      run: |
        az webapp create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --plan ${{ secrets.AZURE_APP_SERVICE_PLAN }} --name ${{ secrets.AZURE_WEB_APP_NAME }} --deployment-container-image-name ${{ secrets.DOCKER_USERNAME }}/your-repo:latest
